### ISSUE TITLE
Update to Rust edition 2018

### ISSUE THREAD

**Issue by kstrafe** [magiclen/pipe-logger-lib#1]
This would remove stuff like `extern crate`.

**Comment by magiclen** [comment]
Why you want to remove `extern crate`?

**Comment by kstrafe** [comment]
Because it's not modern Rust.

**Comment by magiclen** [comment]
`extern crate` is not deprecated in Rust 2018. It just can be ignored in some cases.

**Comment by kstrafe** [comment]
Are you unwilling to modernize in any way @magiclen?

**Comment by magiclen** [comment]
I would like to keep my projects up-to-date, but this, I don't see where is old.

**Comment by kstrafe** [comment]
Then I'll write my own.
